server:
  port: 4044

spring:
  application:
    name: df702
  datasource:
    username: ${TAATTA_POSTGRES_USER}
    password: ${TAATTA_POSTGRES_PASSWORD}
    url: jdbc:postgresql://${TAATTA_POSTGRES_HOST}:${TAATTA_POSTGRES_PORT}/df702
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  zipkin:
    base-url: http://localhost:9411/

logging:
  config: classpath:logback-prod.xml