server:
  port: 4042

spring:
  application:
    name: wqm101
  datasource:
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/wqm101
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411/
logging:
  config: classpath:logback.xml