server:
  port: 4042

spring:
  application:
    name: wqm101
  datasource:
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://localhost:5432/wqm101
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  zipkin:
    base-url: http://localhost:9411/
logging:
  config: classpath:logback-prod.xml