server:
  port: 4042

spring:
  application:
    name: wqm101
  datasource:
    username: ${TAATTA_POSTGRES_USER}
    url: jdbc:postgresql://${TAATTA_POSTGRES_HOST}:${TAATTA_POSTGRES_PORT}/wqm101
    password: ${TAATTA_POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        jdbc:
          time_zone: 'UTC'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411/
logging:
  config: classpath:logback.xml
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true