services:
  collector:
    build:
      context: .
      target: collector
    command: java -jar /usr/local/taatta/collector.jar
    environment:
      - MOSQUITTO_HOST=${MOSQUITTO_HOST}
    depends_on:
      - mosquitto
#  rhf1s001:
#    build:
#      context: .
#      target: rhf1s001
#    command: java -jar -Dspring.profiles.active=prod /usr/local/taatta/rhf1s001.jar
#  tbs220:
#    build:
#      context: .
#      target: tbs220
#    command: java -jar -Dspring.profiles.active=prod /usr/local/taatta/tbs220.jar

  # Chirpstack containers
  # Based on the official template docker-compose.yml at
  # https://github.com/chirpstack/chirpstack-docker/blob/v3/docker-compose.yml
#  chirpstack-network-server:
#    image: chirpstack/chirpstack-network-server:3
#    volumes:
#      - ./configuration/chirpstack-network-server/chirpstack-network-server.toml:/etc/chirpstack-network-server/chirpstack-network-server.toml
#    depends_on:
#      - postgresql
#      - mosquitto
#  chirpstack-application-server:
#    image: chirpstack/chirpstack-application-server:3
#    ports:
#      - 8080:8080
#    volumes:
#      - ./configuration/chirpstack-application-server/chirpstack-application-server.toml:/etc/chirpstack-application-server/chirpstack-application-server.toml
#    depends_on:
#      - chirpstack-network-server
#  chirpstack-gateway-bridge:
#    image: chirpstack/chirpstack-gateway-bridge:3
#    ports:
#      - 1700:1700/udp
#    volumes:
#      - ./configuration/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml:/etc/chirpstack-gateway-bridge/chirpstack-gateway-bridge.toml
#    depends_on:
#      - mosquitto
  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
#  redis:
#    image: redis:5-alpine
#    volumes:
#      - redisdata:/data
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1883:1883
    volumes:
      - ./configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  postgresqldata:
  redisdata: