services:
  collector:
    build:
      context: .
      target: collector
    command: java -jar -Dspring.profiles.active=prod /usr/local/taatta/collector.jar
    restart: unless-stopped
#  df702:
#    build:
#      context: .
#      target: df702
#    command: java -jar -Dspring.profiles.active=prod /usr/local/taatta/df702.jar
#    restart: unless-stopped
#  pcr2:
#    build:
#      context: .
#      target: pcr2
#    command: java -jar -Dspring.profiles.active=prod /usr/local/taatta/pcr2.jar
#    restart: unless-stopped
  rhf1s001:
    build:
      context: .
      target: rhf1s001
    command: java -jar -Dspring.profiles.active=prod /usr/local/taatta/rhf1s001.jar
    restart: unless-stopped
  tbs220:
    build:
      context: .
      target: tbs220
    command: java -jar -Dspring.profiles.active=prod /usr/local/taatta/tbs220.jar
    restart: unless-stopped
#  wqm101:
#    build:
#      context: .
#      target: wqm101
#    command: java -jar -Dspring.profiles.active=prod /usr/local/taatta/wqm101.jar
#    restart: unless-stopped

  # Chirpstack containers
  # Based on the official template docker-compose.yml at
  # https://github.com/chirpstack/chirpstack-docker/blob/master/docker-compose.yml
  chirpstack:
    image: chirpstack/chirpstack:4
    command: -c /etc/chirpstack
    restart: unless-stopped
    volumes:
      - ./chirpstack/configuration/chirpstack:/etc/chirpstack
      - ./chirpstack/lorawan-devices:/opt/lorawan-devices
    depends_on:
      - postgres
      - mosquitto
      - redis
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
    ports:
      - 8080:8080
  chirpstack-gateway-bridge-eu868:
    image: chirpstack/chirpstack-gateway-bridge:4
    restart: unless-stopped
    ports:
      - 1700:1700/udp
    volumes:
      - ./chirpstack/configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto
  chirpstack-rest-api:
    image: chirpstack/chirpstack-rest-api:4
    restart: unless-stopped
    command: --server chirpstack:8080 --bind 0.0.0.0:8090 --insecure
    ports:
      - 8090:8090
    depends_on:
      - chirpstack
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./chirpstack/configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./chirpstack/configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  postgresqldata:
  redisdata: