spring:
  application:
    name: collector
server:
  port: 3030
logging:
  config: classpath:logback-prod.xml
smart-city:
  broker-url: tcp://${TAATTA_MOSQUITTO_HOST}:${TAATTA_MOSQUITTO_PORT}
  # authentication is optional -- default to null if not present
  # https://stackoverflow.com/questions/23348061/how-to-define-value-as-optional
  broker-username: ${TAATTA_MOSQUITTO_USER:#{null}}
  broker-password: ${TAATTA_MOSQUITTO_PASSWORD:#{null}}
