spring:
  application:
    name: collector
  zipkin:
    base-url: http://10.130.1.150:9411/

server:
  port: 3030

logging:
  config: classpath:logback.xml

smart:
  city:
    broker:
      url: tcp://10.130.1.150:1883


