server:
  port: 4046

spring:
  application:
    name: tbs220
  datasource:
    username: ${TAATTA_POSTGRES_USER}
    url: jdbc:postgresql://${TAATTA_POSTGRES_HOST}:5432/tbs220
    password: ${TAATTA_POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  zipkin:
    base-url: http://localhost:9411/
logging:
  config: classpath:logback-prod.xml