server:
  port: 4046

spring:
  application:
    name: tbs220
  datasource:
    username: ${TAATTA_POSTGRES_USER}
    url: jdbc:postgresql://${TAATTA_POSTGRES_HOST}:${TAATTA_POSTGRES_PORT}/tbs220
    password: ${TAATTA_POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        jdbc:
          time_zone: 'UTC'
    hibernate:
      ddl-auto: update
    show-sql: 'false'

logging:
  config: classpath:logback-prod.xml
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true