server:
  port: 4050
spring:
  application:
    name: athom-smart-plug
  datasource:
    username: ${TAATTA_POSTGRES_USER}
    url: jdbc:postgresql://${TAATTA_POSTGRES_HOST}:${TAATTA_POSTGRES_PORT}/athom_smart_plug
    password: ${TAATTA_POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        jdbc:
          time_zone: 'UTC'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'

logging:
  config: classpath:logback.xml
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
smart-city:
  device-management:
    enabled: ${TAATTA_ENABLE_DEVICE_MANAGEMENT:#{true}}
    url: ${TAATTA_DEVICE_MANAGEMENT_URL:#{"http://localhost:4100"}}
