server:
  port: 5042

spring:
  application:
    name: ems701
  datasource:
    username: 'mahabub'
    url: jdbc:postgresql://localhost:5432/ems701
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  zipkin:
    base-url: http://localhost:9411/
logging:
  config: classpath:logback-prod.xml